# Generated by Django 3.2.21 on 2023-10-08 14:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('hit', models.IntegerField()),
                ('like', models.IntegerField()),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
