# Generated by Django 3.2.21 on 2023-10-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
