# Generated by Django 3.2.21 on 2023-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20231130_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_address',
            field=models.URLField(null=True),
        ),
    ]
